### ISSUE TITLE
ERROR: Could not build wheels for py-find-1st which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by cbitsakou** [roebel/py_find_1st#11] opened 2021-07-05 18:17 UTC
Hello, 
I am trying to install the project and I get the error "ERROR: Could not build wheels for py-find-1st which use PEP 517 and cannot be installed directly". I have a macOS and I am trying to install the project in a a conda environment with python 3.8.10. I tried pip install --no-build-isolation py_find_1st which I saw was the solution in a similar case, but unfortunately did not work for me. Could you please help me?

**Comment by roebel** [comment] 2021-07-18 16:38
Hello, I am unfortunately not able to see what your problem could be. For me things seem to build fine under python 3.8 with pip21.1.3. I have precompiled anaconda packages available in the channel roebel [here](https://anaconda.org/roebel/py_find_1st). The package for python 3.8 was indeed missing but I just compiled and uploaded it. So you should be able to use conda to install it into your environment like this

```
 conda install -c roebel py_find_1st 
```

Let me know if this helps.

**Comment by cbitsakou** [comment] 2021-07-18 19:08
Hello, the issue is now solved! thank you very much!

**Comment by samgermain** [comment] 2021-07-19 20:26
Having the same issue

This is my process.

I start a new aws t2.micro ec2 on ubuntu20 and run this script


```
sudo apt-get update
sudo apt-get install gcc
sudo apt-get install python3.9
sudo apt-get install python3.9-venv
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py > get-pip.py
python3.9 get-pip.py
sudo apt-get install python-dev
sudo apt-get install python3-dev
python3.9 -m pip install --upgrade pip
python3.9 -m pip install --upgrade pip setuptools
python3.9 -m pip install --upgrade wheel
python3.9 -m pip install testresources
sudo apt-get install build-essential
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev wget liblzma-dev lzma
sudo apt-get install python3-devel
python3.9 -m pip install p5py
python3.9 -m pip install PEP517
python3.9 -m pip install py-find-1st
```

I get this error output

    Building wheels for collected packages: py-find-1st
      Building wheel for py-find-1st (PEP 517) ... error
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3.9 /home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp47_3kk6k
           cwd: /tmp/pip-install-pvu0gblm/py-find-1st_36eb63373254485b8448e2b46d13c71f
      Complete output (20 lines):
      /tmp/pip-build-env-qm53q7xb/overlay/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/utils_find_1st
      copying utils_find_1st/__init__.py -> build/lib.linux-x86_64-3.9/utils_find_1st
      running build_ext
      check for clang compiler ... no
      building 'find_1st' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/utils_find_1st
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-qm53q7xb/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-3.9/utils_find_1st/find_1st.o
      utils_find_1st/find_1st.cpp:3:10: fatal error: Python.h: No such file or directory
          3 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      ----------------------------------------
      ERROR: Failed building wheel for py-find-1st
    Failed to build py-find-1st
    ERROR: Could not build wheels for py-find-1st which use PEP 517 and cannot be installed directly

-------------------

If you would like to reproduce the error, you can start a t2.micro ec2 running ubuntu20 and run the script listed above

**Comment by samgermain** [comment] 2021-07-19 20:31
It looks like `sudo apt install libpython3.9-dev` is 1 solution

-------------

I think `sudo apt install gcc` also helped

**Comment by roebel** [comment] 2021-07-20 10:45
Hello samgermain

The error message is
```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-qm53q7xb/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-3.9/utils_find_1st/find_1st.o
  utils_find_1st/find_1st.cpp:3:10: fatal error: Python.h: No such file or directory
      3 | #include "Python.h"
```

So in some way or another the python files or compilers are not available.

> It looks like sudo apt install libpython3.9-dev is 1 solution

This obviously depends on the environment you work in.  You may see this thread 
https://github.com/freqtrade/freqtrade/issues/3491# for some problems and solutions in a variety of environments.

As these problems don't seem to be related to anything in py_find_1st I will close the issue.
Best

**Closed as completed by roebel** 2021-07-20 10:45 UTC
